### ISSUE TITLE
do not allow users to vote on their own comments

### ISSUE THREAD

**Issue by xiaowuc1** [DMOJ/online-judge#1517]
probably a prerequisite before #839 can be implemented?

**Comment by TheAvidDev** [comment]
Most platforms allow this and it's not worth the UI change -- having some comments not have up/down vote buttons or graying them out creates inconsistency.

The solution is to either assume a default or ignore a user's own +1 for reputation.

**Comment by Harry7557558** [comment]
I think there should be an option to turn off a user's right to vote or ignore the user's votes in reputation calculation. Some users vote for their comments using alternate accounts.

Also, seems like some people's comments get unusually high or low votes even though the comment content isn't really good or bad. Implementing a comment-based reputation may encourage users to think before they vote for a comment.

**Comment by TheAvidDev** [comment]
A PR for this [exists](https://github.com/DMOJ/online-judge/pull/1384).

> I think there should be an option to turn off a user's right to vote or ignore the user's votes in reputation calculation.

This can almost be done already. Right now, the calculation assumes that users +1 their own comment.

> Some users vote for their comments using alternate accounts.

Nothing we can really do about it.

> Also, seems like some people's comments get unusually high or low votes even though the comment content isn't really good or bad.

Yeah, I find most votes to be pretty random.

> Implementing a vote-based reputation may encourage users to think before they vote for a comment.

I hope so, but I doubt it will change anything. I don't think people will suddenly think before they vote because someone else's reputation is affected. And for you own comments, anyone who does care will logically comment less.
