### ISSUE TITLE
Add a button to check the entered password.

### ISSUE THREAD

**Issue by k906506** [DMOJ/online-judge#1816]
In now, user cannot see the entered password In the login page.
Add a visible button so that user can see the entered password.

**Comment by Diwakar-Gupta** [comment]
I have created a button on the bottom of password field.
I wonder if this is fine or a floating button on the right end of password field will be better.

<img width="267" alt="Screenshot 2022-11-04 at 9 45 11 AM" src="https://user-images.githubusercontent.com/39624018/199885828-7de04218-2265-4870-a03c-56d39e62b47d.png">

<img width="272" alt="Screenshot 2022-11-04 at 9 39 17 AM" src="https://user-images.githubusercontent.com/39624018/199884212-e39f30b7-d44d-40e6-a8a3-b9ef8a447306.png">

**Comment by quantum5** [comment]
This is a terrible idea because it's almost impossible to get right. Any mistake could result in the password being stored as plaintext autocomplete, which is a terrible security situation. While it may be possible to coerce all known browsers into not storing the password as plaintext, the autocomplete is just a blackbox from the webapp's perspective and there is no guarantee that future browser versions will work the same way. The only possible secure implementation is one by the browser itself.
