### ISSUE TITLE
Adding Greek Localization

### ISSUE THREAD

**Issue by ptheoch** [DMOJ/online-judge#1893]
Hello!
We are willing to contribute Greek (Hellenic) localization to this great project.
We are not entirely sure how to start the process. Should we first make a request via https://crowdin.com/ ?

**Comment by Xyene** [comment]
Hi! Thanks for offering -- I've enabled Greek as a target language on https://translate.dmoj.ca/. The translations get automatically synced to https://github.com/DMOJ/online-judge/pull/1891, so please give us a ping on that thread when you are ready for it to be merged (and keep an eye out for build errors preventing it to be merged, oftentimes this happens if you forget to fill in a plural form for a string).

**Comment by ptheoch** [comment]
Hi! We think we are ready to have it merged to master!
