### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by WallE256** [DMOJ/online-judge#230]
Making a Docker Compose file would automate the tedious and complicated process of installing DMOJ site. Along with #226, it would fix #191 .
Ansible is also a option.

/cc @Xyene @quantum5

**Comment by airob0t** [comment]
I made a Dockerfile to build the site.It can work after config the db and restart the supervisorsd,nginx .
Because I'm not familiar with Docker, it should be optimized。
[dmoj_docker](https://github.com/airob0t/dmoj_docker)

**Comment by Xyene** [comment]
Hi,

So, I gave your Docker a go, since building DMOJ with Docker is something that would definitely help people out with installations.

I went through with it as much as my time allowed, and did get it working. Some notes:

* MySQL *really* needs to be version 5.6 or later, otherwise Django's redirect module migration fails with `django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')` (it tries to create an index on a field of length 200) when using `utf8mb4` as the charset (and using `utf8` instead is an unacceptable workaround). This isn't an issue with your Dockerfile since the installation of MySQL is left to the user, but it's important to note anyway since the error is arcane to decipher.
* `apt` shouldn't be used in the Dockerfile, as it complains loudly about not being connected to a TTY (it's a frontend for `apt-get`, so `apt-get` should be used in scripts instead).
* `vim` shouldn't be installed by the Dockerfile; let the user `docker attach` and install their editor of choice if they really need to.
* It should be possible to install MySQL automatically, and indeed I think this would need to be done for this to become viable. Using a fixed password probably wouldn't be an issue since MySQL will live entirely isolated within Docker, but I may be wrong on that note.
* There's a whole lot of other services that need to be installed for DMOJ to be operating properly ([`camo`](https://github.com/atmos/camo), [`texoid`](https://github.com/DMOJ/texoid), [`mathoid`](https://github.com/wikimedia/mathoid), others I'm forgetting) as well as some more binaries (e.g. `phantomjs` for the site to be able to output PDFs). They're less important than having an otherwise-functional install, though.

Anyway, I think this is worth looking into.

**Comment by TheAvidDev** [comment]
#### This is heavily inspired from @Ninjaclasher's [docker files](https://github.com/Ninjaclasher/dmoj-docker) used for running DMOJ in docker:

I have created my own set of docker files [here](https://github.com/TheAvidDev/docker-files/tree/dmoj) which I plan to maintain and update in the future. It currently runs the base [online-judge](https://github.com/DMOJ/online-judge), along with the bridge, an [nginx](https://www.nginx.com/) instance, [database](https://mariadb.org/), [celery](http://docs.celeryproject.org/en/latest/index.html), [redis](https://redis.io/), [mathoid](https://github.com/wikimedia/mathoid), and [phantomjs](https://github.com/ariya/phantomjs). The images have also been scaled down in size using [`alpine`](https://hub.docker.com/_/alpine/) and `slim` versions where possible. There are also some scripts to help with installation and updating static files and migrations.

In the near future, I plan on adding [texoid](https://github.com/DMOJ/texoid) support, [camo](https://github.com/atmos/camo), and transition from [phantomjs](https://github.com/ariya/phantomjs) to [puppeteer](https://github.com/puppeteer/puppeteer/).

I appreciate any suggestions and contributions.

**Comment by Xyene** [comment]
@Ninjaclasher has been maintaining a Docker image for a while now: https://github.com/Ninjaclasher/dmoj-docker

It's unlikely we'll have the bandwidth to maintain this upstream given we don't -- and won't -- run the site within Docker in prod, but I've heard of plenty of success stories with @Ninjaclasher's Docker image.
