### ISSUE TITLE
Not to show others' source code even if you solve the problem

### ISSUE THREAD

**Issue by jacky030607** [DMOJ/online-judge#836]
I installed this judge for our school club and I intend to use it as a platform for our members to practice coding. However, if I solve a problem, I will be able to see others' source code. I want to disable this feature because I want our members to try to make their code more efficient than just copying the code from other's source code.
Is there an option to disable this feature? Thanks.

**Comment by Xyene** [comment]
This was requested (and subsequently closed) in #430.

While I fully agree it would be a nice feature to have, it would be difficult for us to maintain it in the long run, when we wouldn't actively make use of it on [dmoj.ca](https://dmoj.ca). There's an associated risk of future updates breaking it (since we wouldn't necessarily test it), and we don't want to expose functionality that people think should work, but which... doesn't.

That said, a number of forks have had the same need as you in the past, and it's fairly simple to implement (and maintain) this in a fork. You'd be looking at some minor changes to the visibility checks in https://github.com/DMOJ/site/blob/2e416d7a7ef2100372cd3a467d080dce45e0705d/judge/views/submission.py#L50

and

https://github.com/DMOJ/site/blob/88c1aa319250444230589ade04aef2e8bd68a6b9/judge/jinja2/submission.py#L5

Actually looking at this it seems enough has changed since #430 was opened in 2016 that this might be feasible to implement. If someone were to propose a non-intrusive PR to read some sort of `local_settings.py` entry and branch accordingly, we might be able to continue support for it in master. But if the required changes end up being too extensive, it's probably best to run it as a fork.

**Comment by Ninjaclasher** [comment]
Would it be better for this to implemented on a per-problem basis (a `BooleanField` in the `Problem` model)? In this case, it could be used on DMOJ for code golf problems where you don't want users to be able to see other people's code in case a solution better than the author's solution is found.
