### ISSUE TITLE
Redesign of unauthorized submission page

### ISSUE THREAD

**Issue by J-Song1** [DMOJ/online-judge#894]
Instead of having a SIGSEGV: unauthorized_access page for submissions to problems user has not solved, have a UI that informs user they are unable to view the submission as they have not solved the problem, as well as providing submission's author and problem.

**Comment by Xyene** [comment]
I think this is a good idea, in particular for problems that are otherwise public. (Submissions to private problems should likely still SIGSEGV.) For public problems, the submission IDs can be sniffed out of their respective problem submission lists, so we wouldn't be leaking any information that isn't already public.

**Comment by ehhthing** [comment]
Wouldn't SIGSEGV reveal that the problem exists?

It probably wouldn't be a security problem though.

**Comment by Joon7891** [comment]
Could a UI for private problem submissions be a possibility? I feel like having even just a static webpage informing the user that the problem is private and they do not have access to it gives the site a much more "polished" look, opposed to the blue SIGSEGV page. Or would this pose a security threat with respect to revealing too much information?
